### ISSUE TITLE
Módulo de estadisticas no se puede ejecutar

### ISSUE THREAD

**Issue by Madot10** [PyLovePlus/SanguchitoPlus#11]
Al llamar las funciones:

- tipo_vendidos
```
Traceback (most recent call last):
  File "C:\Users\Miguel\Documents\GitHub\SanguchitoPlus\main.py", line 210, in <module>
    menu_principal()
  File "C:\Users\Miguel\Documents\GitHub\SanguchitoPlus\main.py", line 105, in menu_principal
    submenu_estadisticas(historico_pedidos)
  File "C:\Users\Miguel\Documents\GitHub\SanguchitoPlus\main.py", line 197, in submenu_estadisticas
    mod_estadisticas.tipo_vendidos(historico_pedidos)
  File "C:\Users\Miguel\Documents\GitHub\SanguchitoPlus\estadisticas.py", line 4, in tipo_vendidos
    i, j, ind, dob, tri, total = 0
TypeError: cannot unpack non-iterable int object
```

- ing_mas_vendidos
```
****************************************************************************************************
		 1- Cantidad de Sandwiches por tipo
		 2- Ventas por ingredientes
		 s- Volver a menú principal
Ingrese la opción que desee: 2
Traceback (most recent call last):
  File "C:\Users\Miguel\Documents\GitHub\SanguchitoPlus\main.py", line 210, in <module>
    menu_principal()
  File "C:\Users\Miguel\Documents\GitHub\SanguchitoPlus\main.py", line 105, in menu_principal
    submenu_estadisticas(historico_pedidos)
  File "C:\Users\Miguel\Documents\GitHub\SanguchitoPlus\main.py", line 203, in submenu_estadisticas
    mod_estadisticas.ing_mas_vendidos(historico_pedidos)
  File "C:\Users\Miguel\Documents\GitHub\SanguchitoPlus\estadisticas.py", line 24, in ing_mas_vendidos
    i, j, k, jam, cha, pim, dqs, ace, ppe, sal = 0
TypeError: cannot unpack non-iterable int object
```

**Comment by rsca7213** [comment]
Arreglado por Victoria
