### ISSUE TITLE
Problemas en el modulo de estadisticas

### ISSUE THREAD

**Issue by rsca7213** [PyLovePlus/SanguchitoPlus#12]
Para recrear los errores, primero creamos un pedido de un sandwich triple con jamón.

> ****************************************************************************************************
>                                              Realizar pedido
> ****************************************************************************************************
> Sandwich número 1
> 
> Tipo: Triple ( t ) Doble ( d ) Individual ( i ) --> t
> 
> Ingredientes:
> (ja) Jamón
> (ch) Champiñones
> (pi) Pimentón
> (dq) Doble queso
> (ac) Aceitunas
> (pe) Pepperoni
> (sa) Salchichón
> Indique un ingrediente (enter para terminar) --> ja
> Indique un ingrediente (enter para terminar) --> 
> ----------------------------------------------------------------------------------------------------
> Usted ha seleccionado un sandwich Triple con Jamón
> Subtotal a pagar por un sandwich Triple: 620
> 
> ¿Desea realizar otro pedido? (s/n) --> n

Luego, intentamos imprimir estadísticas.

> ****************************************************************************************************
>                                         Estadísticas
> ****************************************************************************************************
>          1- Cantidad de Sandwiches por tipo
>          2- Ventas por ingredientes
>          s- Volver a menú principal
> 
> Ingrese estadística a visualizar --> 1
> Traceback (most recent call last):
>   File "c:\Users\Ricardo\Desktop\Python Projects\SanguchitoPlus\main.py", line 214, in <module>
>     menu_principal()
>   File "c:\Users\Ricardo\Desktop\Python Projects\SanguchitoPlus\main.py", line 105, in menu_principal
>     submenu_estadisticas(historico_pedidos)
>   File "c:\Users\Ricardo\Desktop\Python Projects\SanguchitoPlus\main.py", line 201, in submenu_estadisticas
>     mod_estadisticas.tipo_vendidos(historico_pedidos)
>   File "c:\Users\Ricardo\Desktop\Python Projects\SanguchitoPlus\estadisticas.py", line 8, in tipo_vendidos
>     if hist_pedidos[i][j] == 'i':
> KeyError: 0

> ****************************************************************************************************
>                                         Estadísticas
> ****************************************************************************************************
>          1- Cantidad de Sandwiches por tipo
>          2- Ventas por ingredientes
>          s- Volver a menú principal
> 
> Opción inválida, por favor ingrese una opción válida!
> Ingrese estadística a visualizar --> 2
> Traceback (most recent call last):
>   File "c:\Users\Ricardo\Desktop\Python Projects\SanguchitoPlus\main.py", line 214, in <module>
>     menu_principal()
>   File "c:\Users\Ricardo\Desktop\Python Projects\SanguchitoPlus\main.py", line 105, in menu_principal
>     submenu_estadisticas(historico_pedidos)
>   File "c:\Users\Ricardo\Desktop\Python Projects\SanguchitoPlus\main.py", line 207, in submenu_estadisticas
>     mod_estadisticas.ing_mas_vendidos(historico_pedidos)
>   File "c:\Users\Ricardo\Desktop\Python Projects\SanguchitoPlus\estadisticas.py", line 28, in ing_mas_vendidos
>     for k in range(0, len(hist_pedidos[i][j])):
> KeyError: 0

**Comment by rsca7213** [comment]
Issue solucionado por Miguel
